# ODAR Configuration File

# Server settings
server_url: "http://localhost:8080/completion"

# Model parameters
max_tokens: 1024
temperature: 1
top_p: 0.95
top_k: 40
repeat_penalty: 1.0
presence_penalty: 0.0
frequency_penalty: 0.0

# Runtime settings
max_iterations: 5
timeout: 120  # seconds
